# Generated by Django 2.2.9 on 2020-02-19 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0092_auto_20190902_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Optional. Other users that may also edit this question.', limit_choices_to=models.Q(teacher__isnull=False), related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
