# Generated by Django 2.2.10 on 2020-05-15 02:30

import django.core.validators
from django.db import migrations, models
import peerinst.models.answer
import peerinst.models.group


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0095_newuserrequest_userurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='semester',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], default='FALL', max_length=6),
        ),
        migrations.AddField(
            model_name='answer',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), peerinst.models.answer.max_value_current_year]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='semester',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], default='FALL', max_length=6),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2015), peerinst.models.group.max_value_current_year]),
            preserve_default=False,
        ),
    ]
