# Generated by Django 2.2.10 on 2020-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0095_newuserrequest_userurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rationale_chosen_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='rationale_shown_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
