# Generated by Django 2.2.10 on 2020-05-21 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import peerinst.models.group


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0095_newuserrequest_userurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='student_group_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peerinst.StudentGroupAssignment'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='semester',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], default='FALL', max_length=6),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='year',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), peerinst.models.group.max_value_current_year]),
        ),
    ]
