# Generated by Django 2.2.10 on 2020-05-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0096_auto_20200521_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroupassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peerinst.StudentGroup'),
        ),
    ]
