# Generated by Django 2.2.14 on 2020-09-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0104_auto_20200814_1203'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations = [
                migrations.RemoveField(
                    model_name='blinkassignment',
                    name='blinkquestions',
                ),
                migrations.RemoveField(
                    model_name='blinkassignment',
                    name='teacher',
                ),
                migrations.RemoveField(
                    model_name='blinkassignmentquestion',
                    name='blinkassignment',
                ),
                migrations.RemoveField(
                    model_name='blinkassignmentquestion',
                    name='blinkquestion',
                ),
                migrations.RemoveField(
                    model_name='blinkquestion',
                    name='question',
                ),
                migrations.RemoveField(
                    model_name='blinkquestion',
                    name='teacher',
                ),
                migrations.RemoveField(
                    model_name='blinkround',
                    name='question',
                ),
            ],
            database_operations = [],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations = [
                migrations.DeleteModel(
                    name='BlinkAnswer',
                ),
                migrations.DeleteModel(
                    name='BlinkAssignment',
                ),
                migrations.DeleteModel(
                    name='BlinkAssignmentQuestion',
                ),
                migrations.DeleteModel(
                    name='BlinkQuestion',
                ),
                migrations.DeleteModel(
                    name='BlinkRound',
                ),
            ],
            database_operations = [
                migrations.AlterModelTable(
                    name='BlinkAnswer',
                    table='blink_blinkanswer',
                ),
                migrations.AlterModelTable(
                    name='BlinkAssignment',
                    table='blink_blinkassignment',
                ),
                migrations.AlterModelTable(
                    name='BlinkAssignmentQuestion',
                    table='blink_blinkassignmentquestion',
                ),
                migrations.AlterModelTable(
                    name='BlinkQuestion',
                    table='blink_blinkquestion',
                ),
                migrations.AlterModelTable(
                    name='BlinkRound',
                    table='blink_blinkround',
                ),
            ],
        )
    ]
