# Generated by Django 2.2.14 on 2020-09-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peerinst', '0105_auto_20200903_1343'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations = [
                migrations.CreateModel(
                    name='BlinkAssignment',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200, verbose_name='Title')),
                        ('key', models.CharField(max_length=8, unique=True)),
                        ('active', models.BooleanField(default=False)),
                    ],
                    options={
                        'verbose_name': 'blink assignment',
                        'verbose_name_plural': 'blink assignments',
                    },
                ),
                migrations.CreateModel(
                    name='BlinkQuestion',
                    fields=[
                        ('current', models.BooleanField(default=True)),
                        ('active', models.BooleanField(default=False)),
                        ('time_limit', models.PositiveSmallIntegerField(null=True, verbose_name='Time limit')),
                        ('key', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                        ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerinst.Question')),
                        ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peerinst.Teacher')),
                    ],
                ),
                migrations.CreateModel(
                    name='BlinkRound',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('activate_time', models.DateTimeField()),
                        ('deactivate_time', models.DateTimeField(null=True)),
                        ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blink.BlinkQuestion')),
                    ],
                ),
                migrations.CreateModel(
                    name='BlinkAssignmentQuestion',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('rank', models.IntegerField()),
                        ('blinkassignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blink.BlinkAssignment')),
                        ('blinkquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blink.BlinkQuestion')),
                    ],
                    options={
                        'ordering': ['rank'],
                    },
                ),
                migrations.AddField(
                    model_name='blinkassignment',
                    name='blinkquestions',
                    field=models.ManyToManyField(through='blink.BlinkAssignmentQuestion', to='blink.BlinkQuestion'),
                ),
                migrations.AddField(
                    model_name='blinkassignment',
                    name='teacher',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peerinst.Teacher'),
                ),
                migrations.CreateModel(
                    name='BlinkAnswer',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('answer_choice', models.PositiveSmallIntegerField(verbose_name='Answer choice')),
                        ('vote_time', models.DateTimeField()),
                        ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blink.BlinkQuestion')),
                        ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blink.BlinkRound')),
                    ],
                ),
            ],
            database_operations = [],
        )
    ]
